[default]
DEBUG = false
TITLE = "Flask API"
EXTENSIONS = [
    "src.application.controllers.home_controller"
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'