[default]
TITLE = "Flask API"
EXTENSIONS = [
    "src.application.controllers.home_controller"
]

[development]
EXTENSIONS = [
    "src.infra.extensions.database",
    "src.infra.extensions.database_init"
]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'